/*

 MAP_TILES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : game_tiles_alt.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map_tilesWidth 20
#define map_tilesHeight 18
#define map_tilesBank 0

extern unsigned char map_tiles[];

/* End of MAP_TILES.H */
