/*

 TITLE_TILES.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : title_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define title_tilesWidth 20
#define title_tilesHeight 18
#define title_tilesBank 0

extern unsigned char title_tiles[];

/* End of TITLE_TILES.H */
